# Titel und Beschreibung
title: "AmFaAn Energy AG – Markteintrittsstrategie für Solarenergie in der Schweiz"
description: "Analyse, Prognose & Handlungsempfehlungen (2015–2030)"

# Einstellungen
layout: page
markdown: kramdown
theme: jekyll-theme-slate
show_downloads: false
