# Titel und Beschreibung
title: "Das Potenzial von Solarenergie in der Schweiz"
description: "Analyse der letzten 10 Jahre & eine Prognose"

# Einstellungen
layout: page
markdown: kramdown
theme: jekyll-theme-slate
show_downloads: false
